# pre-commit.ci config reference: https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
repos:
  # autoformat and lint Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        types_or:
          - python
          - jupyter
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
        types_or:
          - python
          - jupyter
  - repo: https://github.com/executablebooks/mdformat
    # 1.0.0 has some dependency conflicts
    # might need to wait
    rev: "0.7.22"
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-myst
          - mdformat-black
  - repo: https://github.com/google/yamlfmt
    rev: v0.19.0
    hooks:
      - id: yamlfmt
  # Misc autoformatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude_types: [svg, css, json]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.103.0
  #   hooks:
  #     - id: terraform_fmt
  #     - id: terraform_docs
  - repo: local
    hooks:
      - id: tofu-fmt
        name: tofu-fmt
        language: script
        entry: ./tools/tofu-fmt
        pass_filenames: true
        files: \.(tf|tofu|tfvars|(tftest|tofutest|tfmock|tfquery)\.hcl)$
