jupyterhub:
  httpRoute:
    hostnames:
      - aifutureslab-hub.bids.berkeley.edu
  hub:
    config:
      JupyterHub:
        authenticator_class: github
        public_url: https://aifutureslab-hub.bids.berkeley.edu
      GitHubOAuthenticator:
        oauth_callback_url: https://aifutureslab-hub.bids.berkeley.edu/hub/oauth_callback
        allowed_organizations:
          - "bids-access:aifutures-hub-users"
        admin_groups:
          - "admins"
        manage_groups: true
        populate_teams_in_auth_state: true
        scope:
          - "read:email"
          - "read:org"
    extraConfig:
      team_groups: |
        def access_team_groups(auth_state):
          # id of bids-access github organization
          access_org_id = 239249075
          access_teams = []
          for team in auth_state["teams"]:
            if team.get("organization_id") != access_org_id:
              continue
            access_teams.append(team["slug"])

          return access_teams

        c.GitHubOAuthenticator.auth_state_groups_key = access_team_groups
      default_url: |
        def default_url(request):
          if request.current_user and request.current_user.admin:
            return '/hub/admin'
          return '/hub/spawn'

        c.JupyterHub.default_url = default_url
  singleuser:
    image:
      name: ghcr.io/bids/aifutureshub/user
      tag: main
      pullPolicy: Always
    extraFiles:
      opencode:
        mountPath: /etc/opencode/opencode.json
        data:
          $schema: "https://opencode.ai/config.json"
          model: nrp/qwen3
          disabled_providers:
            - opencode
          provider:
            nrp:
              npm: "@ai-sdk/openai-compatible"
              name: NRP
              options:
                baseURL: "https://ellm.nrp-nautilus.io/v1"
                apiKey: "{env:OPENAI_API_KEY}"
              models:
                kimi:
                  name: kimi
                  limit:
                    "context": 262144
                    "output": 32768
                  options:
                    chat_template_kwargs:
                      "thinking": true
                      "preserve_thinking": true
                  variants:
                    instruct:
                      chat_template_kwargs:
                        thinking: false
                        preserve_thinking: false
                qwen3:
                  name: qwen3
                qwen3-small:
                  name: qwen3-small
                gpt-oss:
                  name: gpt-oss
                gemma:
                  name: gemma
                gemma-small:
                  name: gemma-small
                glm-5:
                  name: glm-5
                minimax-m2:
                  name: minimax-m2
jupyterhub-home-nfs:
  prometheusExporter:
    enabled: true
  gke:
    enabled: true
    volumeId: projects/bids-jupyterhub/zones/us-central1-a/disks/hub-nfs-demo
  quotaEnforcer:
    hardQuota: "10" # in GiB
