jupyterhub:
  httpRoute:
    hostnames:
      - aifutureslab-hub.bids.berkeley.edu
  hub:
    config:
      Authenticator:
        enable_auth_state: true
      JupyterHub:
        authenticator_class: github
        public_url: https://aifutureslab-hub.bids.berkeley.edu
      GitHubOAuthenticator:
        oauth_callback_url: https://aifutureslab-hub.bids.berkeley.edu/hub/oauth_callback
        allowed_users:
          # collaboration users must be invalid github usernames
          - _bids-comms
        allowed_organizations:
          - "bids-access:aifutures-hub-users"
        admin_groups:
          - "admins"
        manage_groups: true
        populate_teams_in_auth_state: true
        scope:
          - "user:email"
          - "read:org"
    loadRoles:
      bids-comms:
        scopes:
          - admin-ui
          - servers!user=_bids-comms
        groups:
          - bids-comms
    extraConfig:
      team_groups: |
        def access_team_groups(auth_state):
          # id of bids-access github organization
          access_org_id = 239249075
          access_teams = []
          for team in auth_state["teams"]:
            if team.get("organization_id") != access_org_id:
              continue
            access_teams.append(team["slug"])

          return access_teams

        c.GitHubOAuthenticator.auth_state_groups_key = access_team_groups
      # mount shared directories for the collaboration groups
      # these are the _home_ directories of the collaboration accounts
      shared_directories: |
        collaboration_groups = {
            "bids-comms",
        }

        def mount_collaboration_directories(spawner):
            if not spawner.volume_mounts:
                spawner.volume_mounts = {}
            for group in spawner.user.groups:
                if group.name in collaboration_groups:
                    # mount the user's home in shared/$group
                    # user (home subPath) = _bids-comms
                    # group = bids-comms
                    spawner.volume_mounts[group.name] = {
                        "mountPath": f"/home/jovyan/shared/{group.name}",
                        "name": "home",
                        "subPath": "_" + group.name,
                    }
        c.Spawner.pre_spawn_hook = mount_collaboration_directories
      refresh_user: |
        def refresh_user_hook(authenticator, user, auth_state):
            if user.name.startswith("_"):
                # don't require refresh user auth for collaboration and testing accounts
                # (these aren't github users)
                return True
            # for all other users, refresh as usual
            return None

        c.OAuthenticator.refresh_user_hook = refresh_user_hook
      git_env: |
        # workaround https://github.com/jupyterhub/oauthenticator/pull/820
        def modify_auth_state(authenticator, auth_state):
            if auth_state.get("scope") and len(auth_state["scope"]) == 1:
                auth_state["scope"] = auth_state["scope"][0].split(",")
            return auth_state

        c.GitHubOAuthenticator.modify_auth_state_hook = modify_auth_state

        # populate github env
        def auth_state_hook(spawner, auth_state):
            if not auth_state:
                return
            github_user = auth_state["github_user"]
            spawner.env["GITHUB_TOKEN"] = auth_state["access_token"]
            spawner.env["GIT_AUTHOR_NAME"] = spawner.env["GIT_COMITTER_NAME"] = github_user["name"]
            if github_user["email"]:
                spawner.env["EMAIL"] = github_user["email"]

        c.Spawner.auth_state_hook = auth_state_hook
      default_url: |
        def default_url(request):
          if request.current_user and request.current_user.admin:
            return '/hub/admin'
          return '/hub/spawn'

        c.JupyterHub.default_url = default_url
  singleuser:
    image:
      name: ghcr.io/bids/aifutureshub/user
      tag: main
      pullPolicy: Always
    extraFiles:
      opencode:
        mountPath: /etc/opencode/opencode.json
        data:
          $schema: "https://opencode.ai/config.json"
          model: nrp/qwen3
          disabled_providers:
            - opencode
          provider:
            nrp:
              npm: "@ai-sdk/openai-compatible"
              name: NRP
              options:
                baseURL: "https://ellm.nrp-nautilus.io/v1"
                apiKey: "{env:OPENAI_API_KEY}"
              models:
                kimi:
                  name: kimi
                  limit:
                    "context": 262144
                    "output": 32768
                  options:
                    chat_template_kwargs:
                      "thinking": true
                      "preserve_thinking": true
                  variants:
                    instruct:
                      chat_template_kwargs:
                        thinking: false
                        preserve_thinking: false
                qwen3:
                  name: qwen3
                qwen3-small:
                  name: qwen3-small
                gpt-oss:
                  name: gpt-oss
                gemma:
                  name: gemma
                gemma-small:
                  name: gemma-small
                glm-5:
                  name: glm-5
                minimax-m2:
                  name: minimax-m2
jupyterhub-home-nfs:
  prometheusExporter:
    enabled: true
  gke:
    enabled: true
    volumeId: projects/bids-jupyterhub/zones/us-central1-a/disks/hub-nfs-demo
  quotaEnforcer:
    hardQuota: "10" # in GiB
