#!/bin/bash
set -euo pipefail

if ! which tofu 2>/dev/null; then
  echo 'skipping tofu fmt because `tofu` not found'
  exit 0
fi
set -x
tofu fmt "$@"

for cluster in tf/clusters/*; do
  pushd "$cluster"
  tofu validate
  popd
done

if which tflint 2>/dev/null; then
  tflint --recursive --fix
fi
